name: machine_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - pandas
  - streamlit
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - lightgbm
  - folium
  - mapclassify
  - pip
  - pip:
      - mlflow
      - pydeck
      - watchdog